"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

export default function CompanyProfile(){
 const router=useRouter();
 const [company,setCompany]=useState<any>(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const cid=localStorage.getItem("lead2sales_company_id");if(!cid){router.replace("/onboarding");return;}const {data,error}=await supabase.from("companies").select("*").eq("id",cid).single();if(error){setMsg(error.message);return;}setCompany(data);setName(data?.name||"");setEmail(data?.email||"");})()},[router]);
 async function save(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid)return;setSaving(true);const {data,error}=await supabase.from("companies").update({name:name.trim(),email:email.trim().toLowerCase()||null}).eq("id",cid).select("*").single();if(error)setMsg(error.message);else setCompany(data);setSaving(false);}
 const fields=company?Object.entries(company).filter(([k])=>!["id","created_at","updated_at","name","email"].includes(k)):[];
 return <div className="appPageShell"><aside className="appPageSide"><div className="ccBrand"><div className="ccBrandMark">L2S</div><div><b>Lead2Sales</b><small>AI Sales Platform</small></div></div><nav className="ccNav"><button onClick={()=>router.push("/command-center")}>⌂ Command Center</button><button className="active">🏢 Company Profile</button><button onClick={()=>router.push("/products-catalogue")}>▦ Product Catalogue</button><button onClick={()=>router.push("/command-center")}>◉ Leads</button><button onClick={()=>router.push("/command-center")}>🧾 Quotations</button><button onClick={()=>router.push("/command-center")}>📋 BOQ / Presales</button><button onClick={()=>router.push("/command-center")}>⏰ Follow-ups</button><button onClick={()=>router.push("/command-center")}>⚡ Lead Sources</button></nav></aside><main className="appPageMain"><div className="appPageHeader"><div><span className="ccEyebrow">WORKSPACE · COMPANY</span><h1>Company Profile</h1><p>Your company master data used across leads, quotations and client communication.</p></div><button className="ccGhost" onClick={()=>router.push("/command-center")}>← Command Center</button></div><section className="profileCard"><div className="profileTitle"><div><h2>Company Information</h2><p>Keep these details accurate for sales and quotation workflows.</p></div></div><div className="profileGrid"><label>Company Name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Company Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="sales@company.com" /></label></div><div className="profileActions"><button className="ccPrimary" disabled={saving} onClick={save}>{saving?"Saving…":"Save Company Profile"}</button></div>{msg&&<div className="ccError">{msg}</div>}</section>{company&&<section className="profileCard"><div className="profileTitle"><div><h2>Workspace Data</h2><p>Other fields currently stored for this company.</p></div></div><div className="profileDataGrid">{fields.map(([k,v])=><div key={k}><span>{k.replace(/_/g," ")}</span><b>{typeof v==="object"?JSON.stringify(v):String(v??"—")}</b></div>)}</div></section>}</main></div>;
}