"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

type CompanyForm={name:string;legal_name:string;address:string;phone:string;email:string;gst_number:string;logo_url:string};
const emptyForm:CompanyForm={name:"",legal_name:"",address:"",phone:"",email:"",gst_number:"",logo_url:""};

function ProfileField({label,field,value,type="text",placeholder,onChange}:{label:string;field:keyof CompanyForm;value:string;type?:string;placeholder?:string;onChange:(field:keyof CompanyForm,value:string)=>void}){
 return <label>{label}<input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(field,e.target.value)}/></label>;
}

export default function CompanyProfile(){
 const router=useRouter();
 const [form,setForm]=useState<CompanyForm>(emptyForm);
 const [saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[error,setError]=useState("");
 const [gmail,setGmail]=useState({connected:false,email:null as string|null}),[gmailBusy,setGmailBusy]=useState(false);
 const [inboundEmail,setInboundEmail]=useState(""),[inboundEnabled,setInboundEnabled]=useState(true),[inboundSaving,setInboundSaving]=useState(false);
 useEffect(()=>{(async()=>{const cid=localStorage.getItem("lead2sales_company_id");if(!cid){router.replace("/onboarding");return;}const {data,error}=await supabase.from("companies").select("id,name,legal_name,address,phone,email,gst_number,logo_url").eq("id",cid).single();if(error){setError(error.message);setLoading(false);return;}setForm({name:data?.name||"",legal_name:data?.legal_name||"",address:data?.address||"",phone:data?.phone||"",email:data?.email||"",gst_number:data?.gst_number||"",logo_url:data?.logo_url||""});
   const session=(await supabase.auth.getSession()).data.session; const headers:HeadersInit=session?{Authorization:"Bearer "+session.access_token}:{};
   const [gs,ins]=await Promise.all([fetch("/api/gmail/status?company_id="+encodeURIComponent(cid),{headers}),supabase.from("email_lead_sources").select("inbound_address,enabled").eq("company_id",cid).maybeSingle()]);
   const gd=await gs.json().catch(()=>({})); if(gs.ok)setGmail({connected:!!gd.connected,email:gd.email||null});
   if(ins.data){setInboundEmail(ins.data.inbound_address||"");setInboundEnabled(ins.data.enabled!==false);} setLoading(false);})()},[router]);
 const set=(field:keyof CompanyForm,value:string)=>setForm(prev=>({...prev,[field]:value}));
 async function connectGmail(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid)return;setGmailBusy(true);const s=(await supabase.auth.getSession()).data.session;const r=await fetch("/api/gmail/connect?company_id="+encodeURIComponent(cid),{headers:s?{Authorization:"Bearer "+s.access_token}:{}});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Could not start Gmail connection.");setGmailBusy(false);return;}window.location.href=d.url;}
 async function disconnectGmail(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid)return;setGmailBusy(true);const s=(await supabase.auth.getSession()).data.session;const r=await fetch("/api/gmail/disconnect",{method:"POST",headers:{"Content-Type":"application/json",...(s?{Authorization:"Bearer "+s.access_token}:{})},body:JSON.stringify({company_id:cid})});if(r.ok)setGmail({connected:false,email:null});else setError("Could not disconnect Gmail.");setGmailBusy(false);}
 async function saveInbound(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid||!inboundEmail.trim())return;setInboundSaving(true);const {data:existing}=await supabase.from("email_lead_sources").select("id").eq("company_id",cid).maybeSingle();const payload={company_id:cid,inbound_address:inboundEmail.trim().toLowerCase(),enabled:inboundEnabled,updated_at:new Date().toISOString()};const q=existing?supabase.from("email_lead_sources").update(payload).eq("id",existing.id):supabase.from("email_lead_sources").insert(payload);const {error}=await q;if(error)setError(error.message);else setMsg("Receiving email saved.");setInboundSaving(false);}
 async function save(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid)return;if(!form.name.trim()){setError("Company name is required.");return;}setSaving(true);setError("");setMsg("");const {error}=await supabase.from("companies").update({name:form.name.trim(),legal_name:form.legal_name.trim()||null,address:form.address.trim()||null,phone:form.phone.trim()||null,email:form.email.trim().toLowerCase()||null,gst_number:form.gst_number.trim().toUpperCase()||null,logo_url:form.logo_url.trim()||null}).eq("id",cid);if(error)setError(error.message);else setMsg("Company profile saved successfully.");setSaving(false);}
 if(loading)return <div className="appPageShell"><main className="appPageMain"><div className="profileCard">Loading company profile…</div></main></div>;
 return <div className="appPageShell"><aside className="appPageSide"><div className="ccBrand"><div className="ccBrandMark">L2S</div><div><b>Lead2Sales</b><small>AI Sales Platform</small></div></div><nav className="ccNav">
   <button onClick={()=>router.push("/command-center")}>⌂ Command Center</button><button className="active">🏢 Company Profile</button><button onClick={()=>router.push("/products-catalogue")}>▦ Product Catalogue</button><button onClick={()=>router.push("/command-center")}>◉ Leads</button><button onClick={()=>router.push("/command-center")}>🧾 Quotations</button><button onClick={()=>router.push("/command-center")}>📋 BOQ / Presales</button><button onClick={()=>router.push("/command-center")}>⏰ Follow-ups</button><button onClick={()=>router.push("/command-center")}>⚡ Lead Sources</button>
 </nav></aside><main className="appPageMain"><div className="appPageHeader"><div><span className="ccEyebrow">WORKSPACE · COMPANY</span><h1>Company Profile</h1><p>Complete company master data used across leads, quotations, BOQ documents and client communication.</p></div><button className="ccGhost" onClick={()=>router.push("/command-center")}>← Command Center</button></div>
 <section className="profileCard"><div className="profileTitle"><div><h2>Company Identity</h2><p>These details appear in quotations and client-facing documents.</p></div></div><div className="profileGrid"><ProfileField label="Company / Brand Name" field="name" value={form.name} placeholder="Synergy DataNetworks" onChange={set}/><ProfileField label="Legal / Registered Name" field="legal_name" value={form.legal_name} placeholder="Legal entity name" onChange={set}/></div></section>
 <section className="profileCard"><div className="profileTitle"><div><h2>Contact & Address</h2><p>Keep client communication and document contact details complete.</p></div></div><div className="profileGrid"><ProfileField label="Company Email" field="email" value={form.email} type="email" placeholder="sales@company.com" onChange={set}/><ProfileField label="Company Phone" field="phone" value={form.phone} type="tel" placeholder="+91 98765 43210" onChange={set}/><label>Registered / Office Address<textarea className="ccFullField" rows={4} value={form.address} placeholder="Complete office address" onChange={e=>set("address",e.target.value)}/></label></div></section>
 <section className="profileCard"><div className="profileTitle"><div><h2>Tax & Branding</h2><p>Used for quotations, invoices and company branding.</p></div></div><div className="profileGrid"><ProfileField label="GST Number" field="gst_number" value={form.gst_number} placeholder="GSTIN" onChange={set}/><ProfileField label="Company Logo URL" field="logo_url" value={form.logo_url} placeholder="https://..." onChange={set}/></div>{form.logo_url&&<div style={{marginTop:16}}><small>Logo preview</small><div style={{marginTop:8}}><img src={form.logo_url} alt="Company logo" style={{maxWidth:180,maxHeight:70,objectFit:"contain"}}/></div></div>}</section>
 <section className="profileCard"><div className="profileTitle"><div><h2>Gmail Sending Account</h2><p>Connect the Gmail account Lead2Sales will use for outgoing quotations and client emails.</p></div><b className={gmail.connected?"ccSuccess":"ccError"}>{gmail.connected?"CONNECTED":"NOT CONNECTED"}</b></div><div className="profileGrid"><label>Sender Email<input value={gmail.email||""} readOnly placeholder="Connect Gmail to load sender email"/></label><div className="profileActions"><button className="ccPrimary" disabled={gmailBusy} onClick={gmail.connected?disconnectGmail:connectGmail}>{gmailBusy?"Please wait…":gmail.connected?"Disconnect Gmail":"Connect Gmail"}</button></div></div></section><section className="profileCard"><div className="profileTitle"><div><h2>Receiving Email / Lead Capture</h2><p>Inbound address used by Resend to create leads automatically.</p></div></div><div className="profileGrid"><label>Receiving Email<input value={inboundEmail} onChange={e=>setInboundEmail(e.target.value)} placeholder="leads@your-inbound-domain"/></label><label><input type="checkbox" checked={inboundEnabled} onChange={e=>setInboundEnabled(e.target.checked)}/> Enable inbound lead capture</label></div><div className="profileActions"><button className="ccPrimary" disabled={inboundSaving} onClick={saveInbound}>{inboundSaving?"Saving…":"Save Receiving Email"}</button></div></section><section className="profileCard"><div className="profileActions"><button className="ccPrimary" disabled={saving} onClick={save}>{saving?"Saving…":"Save Complete Company Profile"}</button></div>{error&&<div className="ccError">{error}</div>}{msg&&<div className="ccSuccess">{msg}</div>}</section>
 </main></div>;
}