"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

const empty={name:"",legal_name:"",address:"",phone:"",email:"",gst_number:"",logo_url:""};

export default function CompanyProfile(){
 const router=useRouter();const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const cid=localStorage.getItem("lead2sales_company_id");if(!cid){router.replace("/onboarding");return;}const {data,error}=await supabase.from("companies").select("id,name,legal_name,address,phone,email,gst_number,logo_url").eq("id",cid).single();if(error){setMsg(error.message)}else if(data){setForm({...empty,...data})}setLoading(false)})()},[router]);
 function set(k:keyof typeof empty,v:string){setForm(x=>({...x,[k]:v}))}
 async function save(){const cid=localStorage.getItem("lead2sales_company_id");if(!cid)return;setSaving(true);setMsg("");const payload={name:form.name.trim(),legal_name:form.legal_name.trim()||null,address:form.address.trim()||null,phone:form.phone.trim()||null,email:form.email.trim().toLowerCase()||null,gst_number:form.gst_number.trim().toUpperCase()||null,logo_url:form.logo_url.trim()||null};const {error}=await supabase.from("companies").update(payload).eq("id",cid);setMsg(error?error.message:"Company profile saved successfully.");setSaving(false);}
 const Field=({label,k,placeholder}:{label:string;k:keyof typeof empty;placeholder?:string})=><label className="profileField">{label}<input value={form[k]} placeholder={placeholder} onChange={e=>set(k,e.target.value)}/></label>;
 return <div className="appPageShell"><aside className="appPageSide"><div className="ccBrand"><div className="ccBrandMark">L2S</div><div><b>Lead2Sales</b><small>AI Sales Platform</small></div></div><nav className="ccNav"><button onClick={()=>router.push("/command-center")}>⌂ Command Center</button><button className="active">🏢 Company Profile</button><button onClick={()=>router.push("/products-catalogue")}>▦ Product Catalogue</button><button onClick={()=>router.push("/command-center")}>◉ Leads</button><button onClick={()=>router.push("/command-center")}>🧾 Quotations</button><button onClick={()=>router.push("/command-center")}>📋 BOQ / Presales</button><button onClick={()=>router.push("/command-center")}>⏰ Follow-ups</button><button onClick={()=>router.push("/command-center")}>⚡ Lead Sources</button></nav></aside><main className="appPageMain"><div className="appPageHeader"><div><span className="ccEyebrow">WORKSPACE · COMPANY MASTER</span><h1>Company Profile</h1><p>One source of truth for quotations, BOQs, emails, documents and client communication.</p></div><button className="ccGhost" onClick={()=>router.push("/command-center")}>← Command Center</button></div>{loading?<section className="profileCard">Loading company profile…</section>:<><section className="profileCard"><div className="profileTitle"><div><h2>Company Information</h2><p>Basic identity and official communication details.</p></div></div><div className="profileGrid"><Field label="Display / Trading Name" k="name" placeholder="Your company name"/><Field label="Legal Company Name" k="legal_name" placeholder="Registered legal name"/><Field label="Official Email" k="email" placeholder="sales@company.com"/><Field label="Primary Phone" k="phone" placeholder="+91 …"/><label className="profileField profileWide">Registered Office / Address<textarea value={form.address} placeholder="Complete company address" onChange={e=>set("address",e.target.value)}/></label><Field label="GSTIN" k="gst_number" placeholder="GST registration number"/></div></section><section className="profileCard"><div className="profileTitle"><div><h2>Branding</h2><p>Used later on quotation, proposal and other generated documents.</p></div></div><div className="profileGrid"><label className="profileField profileWide">Company Logo URL<input value={form.logo_url} placeholder="https://…" onChange={e=>set("logo_url",e.target.value)}/></label></div>{form.logo_url&&<img className="companyLogoPreview" src={form.logo_url} alt="Company logo preview" />}</section><div className="profileActions"><button className="ccPrimary" disabled={saving} onClick={save}>{saving?"Saving…":"Save Company Profile"}</button></div>{msg&&<div className={msg.includes("successfully")?"ccSuccess":"ccError"}>{msg}</div>}</>}</main></div>;
}