import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type PdfItem = {
  item_name?: string;
  specification?: string;
  quantity?: number;
  unit?: string;
  unit_price?: number;
};

type PdfInput = {
  companyName: string;
  quotationNo: string;
  customerName: string;
  requirement: string;
  items: PdfItem[];
  subtotal: number;
  gstPercent: number;
  gstAmount: number;
  grandTotal: number;
};

function money(n:number){ return "INR "+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0}); }

function wrap(text:string,max:number){
  const words=String(text||"").replace(/\s+/g," ").trim().split(" ");
  const out:string[]=[]; let line="";
  for(const word of words){
    const next=line?line+" "+word:word;
    if(next.length>max){if(line)out.push(line);line=word;}else line=next;
  }
  if(line)out.push(line);
  return out.length?out:[""];
}

export async function createQuotationPdf(input:PdfInput){
  const pdf=await PDFDocument.create();
  const font=await pdf.embedFont(StandardFonts.Helvetica);
  const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageW=595.28,pageH=841.89;
  const margin=36;
  let page=pdf.addPage([pageW,pageH]);
  let y=pageH-margin;

  const newPage=()=>{page=pdf.addPage([pageW,pageH]);y=pageH-margin;};
  const ensure=(h:number)=>{if(y-h<margin){newPage();}};
  const text=(s:string,x:number,size=9,f=font)=>{page.drawText(String(s||""),{x,y,size,font:f,color:rgb(.08,.08,.08)});};
  const line=(x1:number,y1:number,x2:number,y2:number)=>page.drawLine({start:{x:x1,y:y1},end:{x:x2,y:y2},thickness:.7,color:rgb(.75,.75,.75)});

  text(input.companyName,margin,y,20,bold); y-=25;
  text("QUOTATION",margin,y,12,bold); text(input.quotationNo,pageW-margin-120,y,10,bold); y-=18;
  line(margin,y,pageW-margin,y); y-=18;

  text("Bill To",margin,y,9,bold); y-=14;
  text(input.customerName,margin,y,10,bold); y-=13;
  for(const l of wrap(input.requirement,90).slice(0,4)){text(l,margin,y,8);y-=11;}
  y-=10;

  const cols=[margin,margin+28,margin+205,margin+280,margin+320,margin+385, pageW-margin];
  const headerH=22;
  const drawHeader=()=>{
    ensure(headerH); page.drawRectangle({x:margin,y:y-headerH,width:pageW-2*margin,height:headerH,color:rgb(.94,.94,.94),borderColor:rgb(.75,.75,.75),borderWidth:.7});
    text("#",cols[0]+6,y-15,8,bold); text("Item",cols[1]+4,y-15,8,bold); text("Specification",cols[2]+4,y-15,8,bold); text("Qty",cols[3]+4,y-15,8,bold); text("Unit",cols[4]+4,y-15,8,bold); text("Rate",cols[5]+4,y-15,8,bold); y-=headerH;
  };
  drawHeader();

  let index=1;
  for(const item of input.items.filter(x=>String(x.item_name||"").trim())){
    const nameLines=wrap(item.item_name||"",24);
    const specLines=wrap(item.specification||"",24);
    const rows=Math.max(nameLines.length,specLines.length,1);
    const rowH=Math.max(18,rows*10+8);
    if(y-rowH<margin+40){newPage();drawHeader();}
    page.drawRectangle({x:margin,y:y-rowH,width:pageW-2*margin,height:rowH,borderColor:rgb(.82,.82,.82),borderWidth:.5});
    text(String(index++),cols[0]+6,y-13,8);
    nameLines.forEach((v,i)=>text(v,cols[1]+4,y-13-i*10,7.5));
    specLines.forEach((v,i)=>text(v,cols[2]+4,y-13-i*10,7.5));
    text(String(Number(item.quantity||0)),cols[3]+4,y-13,8);
    text(String(item.unit||"Nos"),cols[4]+4,y-13,8);
    text(money(Number(item.unit_price||0)),cols[5]+4,y-13,7.5);
    y-=rowH;
  }

  ensure(105); y-=15;
  const totalX=pageW-margin-170;
  text("Subtotal",totalX,y,9,bold); text(money(input.subtotal),pageW-margin-80,y,9,bold); y-=15;
  text("GST ("+input.gstPercent+"%)",totalX,y,9); text(money(input.gstAmount),pageW-margin-80,y,9); y-=18;
  line(totalX,y+8,pageW-margin,y+8); y-=5;
  text("Grand Total",totalX,y,12,bold); text(money(input.grandTotal),pageW-margin-90,y,12,bold); y-=30;
  text("Terms & Conditions",margin,y,9,bold); y-=14;
  for(const t of [
    "Prices and taxes are as stated in this quotation.",
    "Final quantities and technical specifications are subject to site verification where applicable.",
    "Delivery, installation and commissioning are as per the agreed scope.",
  ]){for(const l of wrap(t,95)){text("• "+l,margin,y,7.5);y-=10;}y-=2;}
  y=margin+10;
  text("Generated by Lead2Sales",margin,y,7);
  return Buffer.from(await pdf.save()).toString("base64");
}
